version: '3.8'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_USERNAME=admin'
      - 'POSTGRESQL_PASSWORD=admin'
      - 'POSTGRESQL_DATABASE=api'

volumes:
  postgresql_data:
    driver: local
